name: Sincronizar Leads RD para Notion

on:
  workflow_dispatch:
  schedule:
    - cron: '*/55 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Este passo de diagnóstico pode ser removido após confirmarmos que tudo funciona
      - name: Diagnosticar Segredos
        run: |
          if [ -z "${{ secrets.GDRIVE_CREDENTIALS }}" ]; then echo "ERRO DE DIAGNÓSTICO: O segredo GDRIVE_CREDENTIALS está VAZIO ou NÃO FOI ENCONTRADO."; else echo "SUCESSO: O segredo GDRIVE_CREDENTIALS foi encontrado."; fi
          if [ -z "${{ secrets.GDRIVE_TOKEN_JSON }}" ]; then echo "ERRO DE DIAGNÓSTICO: O segredo GDRIVE_TOKEN_JSON está VAZIO ou NÃO FOI ENCONTRADO."; else echo "SUCESSO: O segredo GDRIVE_TOKEN_JSON foi encontrado."; fi
          if [ -z "${{ secrets.BOTCONVERSA_API_KEY }}" ]; then echo "ERRO DE DIAGNÓSTICO: O segredo BOTCONVERSA_API_KEY está VAZIO ou NÃO FOI ENCONTRADO."; else echo "SUCESSO: O segredo BOTCONVERSA_API_KEY foi encontrado."; fi
          if [ -z "${{ secrets.WHATSAPP_RECIPIENT_NUMBER }}" ]; then echo "ERRO DE DIAGNÓSTICO: O segredo WHATSAPP_RECIPIENT_NUMBER está VAZIO ou NÃO FOI ENCONTRADO."; else echo "SUCESSO: O segredo WHATSAPP_RECIPIENT_NUMBER foi encontrado."; fi

      - name: Run Python script
        env:
          # --- BLOCO ENV CORRIGIDO ---
          # Os nomes à esquerda do ':' são as variáveis que o script Python vai ler.
          # Os nomes à direita, dentro de ${{...}}, são os nomes dos seus segredos no GitHub.
          # Agora eles estão todos alinhados.
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          RD_CRM_TOKEN: ${{ secrets.RD_CRM_TOKEN }}
          RD_STAGE_ID: ${{ secrets.RD_STAGE_ID }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_TOKEN_JSON: ${{ secrets.GDRIVE_TOKEN_JSON }}
          BOTCONVERSA_API_KEY: ${{ secrets.BOTCONVERSA_API_KEY }}
          WHATSAPP_RECIPIENT_NUMBER: ${{ secrets.WHATSAPP_RECIPIENT_NUMBER }}
        run: python sync_leads.py
