# Nome do Workflow que aparecerá no separador "Actions"
name: Sincronizar Leads do RD Station com o Notion

# Define quando o workflow deve ser executado
on:
  # Permite que seja executado manualmente
  workflow_dispatch:

  # Executa a cada 55 minutos (sintaxe cron)
  schedule:
    - cron: '*/55 * * * *'

# Define os "trabalhos" (jobs) a serem executados
jobs:
  sync:
    # O tipo de máquina virtual que será usada para executar o trabalho
    runs-on: ubuntu-latest

    # Os passos que o trabalho executará em sequência
    steps:
      # 1. Faz o download do código do seu repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Python na máquina virtual
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instala as bibliotecas a partir do requirements.txt <--- CORREÇÃO 1
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3.1 Diagnosticar segredos
      - name: Diagnosticar Segredos
        run: |
          if [ -z "${{ secrets.GDRIVE_CREDENTIALS }}" ]; then echo "ERRO DE DIAGNÓSTICO: O segredo GDRIVE_CREDENTIALS está VAZIO ou NÃO FOI ENCONTRADO."; else echo "SUCESSO: O segredo GDRIVE_CREDENTIALS foi encontrado."; fi
          if [ -z "${{ secrets.GDRIVE_TOKEN_JSON }}" ]; then echo "ERRO DE DIAGNÓSTICO: O segredo GDRIVE_TOKEN_JSON está VAZIO ou NÃO FOI ENCONTRADO."; else echo "SUCESSO: O segredo GDRIVE_TOKEN_JSON foi encontrado."; fi
          if [ -z "${{ secrets.BOTCONVERSA_API_KEY }}" ]; then echo "ERRO DE DIAGNÓSTICO: O segredo BOTCONVERSA_API_KEY está VAZIO ou NÃO FOI ENCONTRADO."; else echo "SUCESSO: O segredo BOTCONVERSA_API_KEY foi encontrado."; fi
          if [ -z "${{ secrets.WHATSAPP_RECIPIENT_NUMBER }}" ]; then echo "ERRO DE DIAGNÓSTICO: O segredo WHATSAPP_RECIPIENT_NUMBER está VAZIO ou NÃO FOI ENCONTRADO."; else echo "SUCESSO: O segredo WHATSAPP_RECIPIENT_NUMBER foi encontrado."; fi

      # 4. Executa o nosso script Python
      - name: Executar script de sincronização
        # Passa TODOS os segredos para o script <--- CORREÇÃO 2
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          RD_CRM_TOKEN: ${{ secrets.RD_CRM_TOKEN }}
          RD_STAGE_ID: ${{ secrets.RD_STAGE_ID }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_TOKEN_JSON: ${{ secrets.GDRIVE_TOKEN_JSON }}
        run: python sync_leads.py
