name: Sincronizar Leads RD para Notion

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        env:
          # --- BLOCO ENV COMPLETO E CORRIGIDO ---
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          RD_CRM_TOKEN: ${{ secrets.RD_CRM_TOKEN }}
          RD_STAGE_ID: ${{ secrets.RD_STAGE_ID }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_CREDENTIALS_JSON: ${{ secrets.GDRIVE_CREDENTIALS }}
          GDRIVE_TOKEN_JSON: ${{ secrets.GDRIVE_TOKEN_JSON }}
          BOTCONVERSA_API_KEY: ${{ secrets.BOTCONVERSA_API_KEY }}
          # A linha abaixo foi removida porque não a estamos a usar mais
          # WHATSAPP_RECIPIENT_NUMBER: ${{ secrets.WHATSAPP_RECIPIENT_NUMBER }}
          # A LINHA MAIS IMPORTANTE A SER ADICIONADA:
          BOTCONVERSA_SUBSCRIBER_ID: ${{ secrets.BOTCONVERSA_SUBSCRIBER_ID }}
        run: python sync_leads.py
